# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: jisaku6def_arm
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - shifted_joint1
    - shifted_joint2
    - shifted_joint3
    - shifted_joint4
    - shifted_joint5
    - shifted_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: jisaku6def_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: shifted_jisaku6dof_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shifted_joint1
      - shifted_joint2
      - shifted_joint3
      - shifted_joint4
      - shifted_joint5
      - shifted_joint6